spring.application.name=auth


spring.datasource.url=postgresql://neondb_owner:npg_Iyf6lpSiL9Qt@ep-billowing-shape-azkl3qd7.c-3.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate Settings
# update: Otomatis membuat/memperbarui tabel di DB sesuai Entity Java
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create-drop

# Menampilkan query SQL asli di terminal (Bagus untuk belajar & analisa query)
spring.jpa.show-sql=true

# Formatting SQL di terminal agar rapi (tidak menyamping)
spring.jpa.properties.hibernate.format_sql=true

# Dialect PostgreSQL untuk Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

Properties
# Tambahkan ini di bagian bawah application.properties
app.jwt.secret=
app.jwt.expiration-ms=864000000
logging.level.org.springframework.web=DEBUG