spring.application.name=auth


spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate Settings
# update: Otomatis membuat/memperbarui tabel di DB sesuai Entity Java
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create-drop

# Menampilkan query SQL asli di terminal (Bagus untuk belajar & analisa query)
spring.jpa.show-sql=true

# Formatting SQL di terminal agar rapi (tidak menyamping)
spring.jpa.properties.hibernate.format_sql=true

# Dialect PostgreSQL untuk Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Tambahkan ini di bagian bawah application.properties
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=864000000
logging.level.org.springframework.web=DEBUG
logging.level.com.zaxxer.hikari=DEBUG